### ISSUE TITLE
Build docker image `main-latest`

### ISSUE THREAD

**Issue by madhulikajc** [StationA/gcsproxy#2]
(and also redeploy `gcsproxy:master-latest` as `gcsproxy:main-latest` as described in:
https://github.com/StationA/stac/issues/106 )

**Comment by jerluc** [comment]
Done!

For future reference @madhulikajc this is normally just done as:

```
docker build -t registry.stationa.io/stationa/gcsproxy:main-latest . && docker push registry.stationa.io/stationa/gcsproxy:main-latest
```
